version: "2"
services:
    gotauth-app:
        image: gotauth
        depends_on:
            - "gotauth-mysql"
        command: ["./wait-for-it.sh", "gotauth-mysql:3306", "--", "yarn", "start:docker"]
        environment:
            - GOT_DB_HOST=gotauth-mysql
            - GOT_DB_PORT=3306
            - GOT_DB_USR=root
            - GOT_DB_PWD=${GOTAUTH_MYSQL_PWD}
        ports:
            - 31701:7001
    gotauth-mysql:
        image: mysql:5.7.20
        environment:
            - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=${GOTAUTH_MYSQL_PWD}
            - MYSQL_DATABASE=gotauth
        ports:
            - 33062:3306
